[package]
name = "hyprland_workspace_display"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.71"
clap = { version = "3.2.23", features = ["derive"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
